Add bookings
Buhanzaz/java-shareit pull request #3
Opened 2023-11-15 14:44 UTC by Buhanzaz

2023-11-16 11:20 UTC, mikita95 requested changes
Все сделано очень хорошо. Оставил лишь небольшие замечания

2023-11-16 11:20 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    BookingService bookingService;
Не хватает модификатора доступа

2023-11-16 11:20 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    @Transactional
Стоит установить read only флаг, так запрос может выполниться эффективнее. Аналогично и в других местах

2023-11-16 11:20 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            switch (state) {
Стоит завести enum для таких случаев

2023-11-16 18:05 UTC, Buhanzaz commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    BookingService bookingService;
Я использую @FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true) Чтобы не прописывать везде модификаторы доступа, но тут убрал конструктор так как сейчас он не нужен

2023-11-17 16:37 UTC, mikita95 approved these changes
Все отлично. Можно мержить пул-реквест

2023-11-17 22:40 UTC, merged