Add docker
Buhanzaz/java-shareit pull request #6
Opened 2023-12-07 00:26 UTC by Buhanzaz

2023-12-08 06:48 UTC, mikita95 requested changes
Все сделано отлично. Оставил лишь небольшие замечания

2023-12-08 06:48 UTC, mikita95 commented on server/pom.xml
> +            <version>1.5.5.Final</version>
Номера версий лучше вынести в свойства pom файла

2023-12-08 06:48 UTC, mikita95 commented on server/src/main/resources/schema.sql
> +                                 item_id bigint,
Можно было бы добавить индексы на некоторые колонки, по которым выполняются запросы, так запросы будут исполнятся эффективнее

2023-12-09 15:58 UTC, TyutterinYakov reviewed
Добрый вечер! В целом - хорошо) Отметил то, что следует исправить и то, что можно сделать лучше - "(предложение)". Хорошего вечера! Если возникнут вопросы по ревью - пиши в пачку, буду рад помочь🌃

2023-12-09 15:58 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/validation/Validator.java
> +    public static void validationTimeFromDto(ClientRequestBookingDto dto) {
(предложение)Эту валидацию можно было бы реализовать с помощью аннотации валидации над классом, чтобы поддерживать декларативный подход https://devcolibri.com/spring-mvc-кастомная-аннотация-для-валидации/
Кстати, если будет интересно то, как реализовать кастомную аннотацию валидации на уровне класса `ClientRequestBookingDto` - можешь чекнуть тут) https://github.com/TyutterinYakov/CustomValidationClassLevel Я написал небольшой примерчик, чтобы было проще разобраться в теме)

2023-12-09 15:58 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/webClient/BasicWebClient.java
> +            headers.set("X-Sharer-User-Id", String.valueOf(userId));
Название заголовка хорошо было бы вынести в отдельный класс в виде статической константы, чтобы в случае изменений - произвести их в одном месте) Кстати, статические константы записываются заглавными буквами, а слова разделяются нижней чертой
https://www.oracle.com/java/technologies/javase/codeconventions-contents.html

Аналогично в других местах)

2023-12-09 15:58 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/user/dto/UserDto.java
>  public class UserDto {
Для валидации почты следует использовать `@Email` в связке с `@NotEmpty`, так как `@Email` допускает не только `null`, но и пустую строку за корректное значение)

2023-12-09 15:58 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/user/dto/UserDto.java
>  public class UserDto {
Хорошо было бы ограничить размеры текстовых полей на основе тех ограничений, которые установлены на уровне таблицы в БД, чтобы заранее откинуть некорректные запросы) Для ограничения количества символов можно использовать `@Size`. Эта аннотация удобна тем, что допускает null, за счет чего при обновлении по значению мы сможем понять, было передано значение или нет)

2023-12-09 15:58 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/request/ItemRequestController.java
> +    ItemRequestClient webClient;
Для соблюдения инкапсуляции - поля класса должны быть приватными)

2023-12-09 15:58 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/item/controller/ItemController.java
> +    ItemClient webClient;
Для соблюдения инкапсуляции - поля класса должны быть приватными)

2023-12-09 15:58 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/exception/controller/ErrorHandler.java
> +public class ErrorHandler {
Так же следует добавить хендлер для обработки всех необработанных исключений, ловить будем `Throwable`, а возвращать статус 500 INTERNAL_SERVER_ERROR

2023-12-09 15:58 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/exception/controller/ErrorHandler.java
> +public class ErrorHandler {
В класс следует добавить логирование) Для этого достаточно использовать аннотацию из lombok ->> `@Slf4j`. Далее в каждый наш хендлер следует добавить логирование сообщения об ошибке)
Также хорошо было бы передать в лог сообщение об ошибке, а можно и весь трейс, чтобы в случае ошибки было проще разобраться, что именно произошло)
Кстати, при логгировании более эффективно использовать не конкатенацию, а заполнитель - placeholder `{}`
Например:
`log.debug("Получен статус 404 Not found {}", ex.getMessage(), ex);`

2023-12-09 15:58 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/exception/controller/ErrorHandler.java
> +    public ErrorResponse handlerForViolationException(ConstraintViolationException exception) {
Так же можно было бы не создавать для каждого исключения, обрабатываемого как `BAD_REQUEST `, отдельные хендлеры, а собрать их в одну группу в `@ExceptionHandler({ConstraintViolationException.class, HttpStatusCodeException.class...})`
А принимаемым аргументом метода-обработчика будет общий класс-родитель - `RuntimeException`.

2023-12-09 15:58 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/item/client/ItemClient.java
> +    public ResponseEntity<?> itemSearch(String itemName, Long userId, Integer from, Integer size) {
Почему бы сразу не проверить полученное значение `text` с помощью `isBlank`, и, если условие будет true, вернуть сразу пустую неизменяемую коллекцию, не обращаясь к серверу, полученную из `List.of()` или `Collections.empty()`)

2023-12-09 15:58 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/booking/dto/BookingWithoutItemDto.java
Действительно ли этот класс требуется в этом подмодуле?) Хорошого было бы его исключить, так как он здесь никак не используется) Аналогично в других местах

2023-12-09 15:58 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/booking/dto/BookingDto.java
Действительно ли этот класс требуется в этом подмодуле?) Хорошого было бы его исключить, так как он здесь никак не используется) Аналогично в других местах

2023-12-09 15:58 UTC, TyutterinYakov commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
Зависимость с валидацей следует исключить, так как теперь вся валидация, которая не требует обращения к БД, должна находиться в модуле `gateway`

2023-12-09 15:58 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/request/dto/ItemRequestDto.java
>  public class ItemRequestDto {
Хорошо было бы исключить лишние поля из класса-DTO, так как, например, при создании нам требуется лишь поле с описанием) Остальные же не требуются. Таким образом мы будем работать только с теми значениями, что требуются в определенной ситуации

Хорошо было бы ограничить размеры текстовых полей на основе тех ограничений, которые установлены на уровне таблицы в БД, чтобы заранее откинуть некорректные запросы) Для ограничения количества символов можно использовать `@Size`


Аннотация `@NotNull` не требуется, так как проверка на null входит в `@NotBlank`

2023-12-09 15:58 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/item/dto/ItemDto.java
>  public class ItemDto {
Хорошо было бы исключить лишние поля из класса-DTO, так как, например, при создании нам требуются лишь поля с описанием, названием и доступностью) Остальные же не требуются. Таким образом мы будем работать только с теми значениями, что требуются в определенной ситуации

Аннотация `@NotNull` не требуется, так как проверка на null входит в `@NotBlank`

Для ` @Length` хорошо было бы указать и группу обновления, так как она должна учитываться и при обновлении, чтобы контролировать размер переданной строки)

2023-12-09 15:58 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/item/dto/CommentDto.java
>  public class CommentDto {
Хорошо было бы исключить лишние поля из класса-DTO, так как, например, при создании нам требуется лишь поле с описанием) Остальные же не требуются. Таким образом мы будем работать только с теми значениями, что требуются в определенной ситуации

Хорошо было бы ограничить размеры текстовых полей на основе тех ограничений, которые установлены на уровне таблицы в БД, чтобы заранее откинуть некорректные запросы) Для ограничения количества символов можно использовать `@Size`


Аннотация `@NotNull` не требуется, так как проверка на null входит в `@NotBlank`

2023-12-09 15:58 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/booking/controller/BookingController.java
> +    BookingClient webClient;
Для соблюдения инкапсуляции - поля класса должны быть приватными)

2023-12-09 15:58 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/booking/controller/BookingController.java
> +@RestController
Аннотация `@RestController` излишня, так как ты уже оборачиваешь возвращаемое значение в тело ответа, используя `ResponseEntity`
Достаточно было бы использовать `@Controller`
https://coderlessons.com/articles/java/raznitsa-mezhdu-restcontroller-i-annotatsiei-controller-v-spring-mvc-i-rest

Аналогично в других местах)

2023-12-10 08:42 UTC, TyutterinYakov approved these changes
Добрый день! Отметил оставшиеся недочеты и предложения по улучшению, но думаю, что ты справишься с ними вне ревью) Успехов в обучении и прекрасного дня! Продуктивной работы над дипломным проектом!🎇🌅

2023-12-10 08:42 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/booking/dto/ClientRequestBookingDto.java
>  public class ClientRequestBookingDto {
Также аннотация `@Future` над `end` излишня, так как сначала будет проведена проверка в кастомной валидации, а после мы перейдем к проверке `start`, которая, если удовлетворяет `@FutureOrPresent`, тогда и `end` будет 
Также проверки `@NotNull` над датами не требуются, так как они присутствуют в кастомном валидаторе)

2023-12-10 08:42 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/item/dto/BookingWithoutItemDto.java
Этот класс DTO также не требуется в этом подмодуле) Его можно было бы исключить

2023-12-10 08:42 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/item/dto/CommentDto.java
> +public class CommentDto {
Хорошо было бы исключить лишние поля из класса-DTO, так как, например, при создании нам требуется лишь поле с текстом комментария) Остальные же не требуются. Таким образом мы будем работать только с теми значениями, что требуются в определенной ситуации

2023-12-10 08:42 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/item/dto/ItemDto.java
>   * TODO Sprint add-controllers.
Если функционал класса реализован - комментарий следует исключить) Либо же необходимо описать то, что остается реализовать)

2023-12-10 08:42 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/item/dto/ItemDto.java
> +    @Size(max = 255, groups = {CreateValidationObject.class}, message = "Вы привыслили лимит в 255 символов")
Для `@Size` должна быть указана и группа обновления, так как при обновлении также важно проверять размер строки)

2023-12-10 08:42 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/item/dto/ItemDto.java
> +    @Size(max = 255, groups = {CreateValidationObject.class}, message = "Вы привыслили лимит в 255 символов")
Для `@Size` должна быть указана и группа обновления, так как при обновлении также важно проверять размер строки)

2023-12-10 08:42 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/request/dto/ItemRequestDto.java
>  public class ItemRequestDto {
Хорошо было бы исключить лишние поля из класса-DTO, так как, например, при создании нам требуется лишь поле с описанием) Остальные же не требуются. Таким образом мы будем работать только с теми значениями, что требуются в определенной ситуации

2023-12-10 08:42 UTC, TyutterinYakov commented on gateway/src/main/java/shareit/gateway/booking/controller/BookingController.java
> +            @RequestParam(defaultValue = "0", required = false) @PositiveOrZero Integer from,
Если указано `defaultValue`, это уже подразумевает, что параметр не является обязательным, следовательно `required = false` не требуется)

2024-02-11 15:29 UTC, merged